version: '3.8'

services:
  web:
    build: .
    container_name: netcut-web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - FLASK_ENV=production
    depends_on:
      - redis
    networks:
      - netcut-network

  redis:
    image: redis:6-alpine
    container_name: netcut-redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - netcut-network

  nginx:
    image: nginx:alpine
    container_name: netcut-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - netcut-network

networks:
  netcut-network:
    driver: bridge

volumes:
  redis-data: 