version: '3.8'

services:
  web:
    build: .
    container_name: netcut-web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - netcut-network

  redis:
    image: redis:6-alpine
    container_name: netcut-redis
    environment:
      - TZ=Asia/Shanghai
    restart: always
    command: redis-server /etc/redis/redis.conf --appendonly yes
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf
    networks:
      - netcut-network

networks:
  netcut-network:
    driver: bridge

volumes:
  redis-data: 
